### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by azzamsa** [DavidMStraub/gramps-webapp#18]
Just to say thanks.

I love to create hundreds of my family lineage on gramps. But the hardest thing is to share the exported png. It's huge and a pain when reading it in small device.

So I am looking a 'cloud' version of gramps, and landed here. I've tried the test app in heroku, and it works great. IMHO it just need some animation when viewing family tree.

Thank you so much for gramps-webapp.

**Comment by DavidMStraub** [comment]
Hi, I'm glad you like it! I actually plan to make a few improvements to it in the next weeks.

**Comment by azzamsa** [comment]
Yeah, most of my family members using their smartphone as daily driver rather than desktop. So asking them to install gramps just in order to make some edit is huge steps.

I think this project is going into right direction.

---

I don't see many attention here, have you share it to social media? or waiting core feature to be completed?

>  I actually plan to make a few improvements to it in the next weeks.

I would like to install and read the code base in the following weeks, hope I can contribute to this awesome project. (I would like to build the similar one, but since it already exists, I can just contribute :) )

**Comment by DavidMStraub** [comment]
> I don't see many attention here, have you share it to social media? or waiting core feature to be completed?

So far I have only announced it on the gramps-devel mailing list, with not too much feedback. Indeed one of the things I wanted to complete before advertising it more broadly is instructions for deployment (after trying out a few possibilities myself).

> I would like to install and read the code base in the following weeks, hope I can contribute to this awesome project. (I would like to build the similar one, but since it already exists, I can just contribute :) )

That would be very welcome! I usually add self-assigned issues before starting to work on a new feature, this way it should be easy to keep track what parts of the code are being worked on.

**Comment by azzamsa** [comment]
> So far I have only announced it on the gramps-devel mailing list, with not too much feedback. Indeed one of the things I wanted to complete before advertising it more broadly is instructions for deployment (after trying out a few possibilities myself).

Alright, we need to reach a point where it's ready for more public announcement. :)

> That would be very welcome! I usually add self-assigned issues before starting to work on a new feature, this way it should be easy to keep track what parts of the code are being worked on.

Ok, that's great.
