### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by xbgmsharp** [DavidMStraub/gramps-webapp#31]
Great job it is a fantastic tool to share genealogy work across the family
How to get the WebUI translated? Should be an environment variables be set? LANG? Is it base on the Accept-Language header?

I can see the request:
```
"GET /api/translate?strings=[%22Birth%20Date%22,%22Death%20Date%22,%22Relationships%22,%22People%22,%22Families%22,%22Dashboard%22,%22Given%20name%22,%22Surname%22,%22Marriage%20Date%22,%22Name%22,%22Father%22,%22Mother%22,%22Married%22,%22Event%22,%22Place%22,%22Description%22,%22Date%22,%22Type%22,%22Events%22,%22Parents%22,%22Siblings%22,%22Children%22,%22Home%20Page%22,%22Details%22,%22in%22,%22Spouses%22,%22Family%20Tree%22,%22Database%20overview%22,%22Number%20of%20individuals%22,%22Number%20of%20families%22,%22Number%20of%20events%22,%22Number%20of%20places%22,%22Places%22,%22Type%22,%22and%22,%22Primary%22,%22Family%22,%22Gallery%22,%22Map%22,%22Unknown%22,%22Custom%22,%22Country%22,%22State%22,%22County%22,%22City%22,%22Parish%22,%22Locality%22,%22Street%22,%22Province%22,%22Region%22,%22Department%22,%22Neighborhood%22,%22District%22,%22Borough%22,%22Municipality%22,%22Town%22,%22Village%22,%22Hamlet%22,%22Farm%22,%22Building%22,%22Number%22,%22Number%20of%20generations:%22,%22Zoom%22,%22Author%22,%22Publication%20info%22,%22Source%22,%22Sources%22,%22Citation%22,%22Citations%22,%22Repository%22,%22Repositories%22,%22Note%22,%22Notes%22,%22Media%22] HTTP/1.1" 200 -
```

**Comment by xbgmsharp** [comment]
PyICU is installed, https://github.com/gramps-project/gramps/blob/9e61809b17b9d6d87cee589cebb703b838e0abfd/gramps/gen/utils/grampslocale.py#L56

I also tried using environment variables as per https://github.com/gramps-project/gramps/blob/master/gramps/cli/argparser.py#L131

Still unable to get the text translate. Any hints?

**Comment by DavidMStraub** [comment]
Indeed setting `LANG` should be enough. In my case setting it to `de_DE.utf8` is enough to get the German strings. This also works in a docker container. Maybe you misspelled the language or the locale is not installed on your system? BTW, since the web app simply uses Gramps' `GRAMPS_LOCALE` global variable, if it works for the GUI it should work for the web app and vice versa, nothing special here.

**Comment by xbgmsharp** [comment]
Thanks does this mean the UI translation is limited to the env at launch?
I guest it link back to web deployment with multiple translation.
Would it be possible to get the translation base on Accept-Language header or via UI menu drop down? There might be users across the world.

**Comment by DavidMStraub** [comment]
That's not possible at the moment but not hard to do. The first step would be to add a parameter to the API endpoint.

**Comment by DavidMStraub** [comment]
I added the language selection on the backend. Unfortunately, this will not work easily for the date formats, as these are localized directly on the backend (while strings are fetched by the frontend).

Note also that I don't think I'll have time to add language selection on the frontend in the near future (low priority for me as my users are monolingual).

**Comment by DavidMStraub** [comment]
Added the "help wanted" label: since my user base is monolingual, I don't have a use case for this, but it would be straightforward to add.

**Comment by DavidMStraub** [comment]
This feature is now implemented in the successor app  [Gramps.js](https://github.com/DavidMStraub/Gramps.js).
